# Generated by Django 2.2.3 on 2020-11-09 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(max_length=1024, verbose_name='descripcion')),
                ('course_number', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='estudiantes')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=200, verbose_name='leccion')),
                ('description', models.TextField(max_length=1024, verbose_name='descripcion')),
                ('lesson_number', models.IntegerField()),
                ('approval_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='pregunta')),
                ('score', models.IntegerField()),
                ('type', models.CharField(choices=[('boolean', 'boolean'), ('multiple', 'multiple'), ('multiple_more_than_ones', 'multiple_more_than_ones'), ('multiple_more_than_ones_all', 'multiple_more_than_ones_all')], default='boolean', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Lessons')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='telefono')),
                ('is_professor', models.BooleanField(default=False, verbose_name='es profesor')),
                ('created', models.DateField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extend', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Questions'),
        ),
    ]
