# Generated by Django 2.2.3 on 2020-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20201109_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='approval_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
